### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/org-cite-csl-activate#1]
Haven't tested it yet, but I'll update this once I do.

In the meantime:

~> Warning: `cursor-sensor-mode' must be turned on for the library to;; work properly.~

~Can you not check this and turn it on if not?~

Also, should you propose `org-cite-get-boundaries` for inclusion in org-cite proper (along with a `get-references-keys` function)? Seems like it might be generally useful?

**Comment by bdarcus** [comment]
Based on general problems I have with `org-cite` font-locking ATM, I think I have a bug either in my config, or in my bleeding-edge Emacs build.

But aside from a screenshot to see what it looks like (which I can't see of course ATM), I've identified the key UX issue to test just above: editing an already-inserted citation.

**Comment by bdarcus** [comment]
FYI, here's my thinking on adding a "follow" processor to `bibtex-actions`:

https://github.com/bdarcus/bibtex-actions/issues/141

My goal would be to couple that with this :-)

**Comment by bdarcus** [comment]
I just had a vague idea (not fully formed, and may not even be a good idea).

Do you have any room to add a hook to allow one to add information to the preview?

For example, maybe I want a user to be able to see if they have a PDF associated with a reference, so they can open that PDF at point?

**Comment by andras-simonyi** [comment]
Thanks for the comments, will try to react shortly. As a first step I added an animation just to show the intended behavior.

**Comment by bdarcus** [comment]
Does one have access to the full reference preview?

**Comment by andras-simonyi** [comment]
> Does one have access to the full reference preview?

yes, currently a  "mini bibilography" containing the full references for the cites in the citation is generated and is shown as a tooltip on mouse hover.

**Comment by andras-simonyi** [comment]
> Still can't get it working, but on the general wish list, I posted some ideas here, based on Zettlr.
> https://lists.gnu.org/archive/html/emacs-orgmode/2021-04/msg00462.html
> I think that's basically what you are doing, so great :-)

Absolutely, I've tried out Zettlr and its behavior with citations looks like a good target.

> I just need to see how well it works in org.
> 
> For example, after you insert the citation, it's rendered as a citation. But how does one then edit that citation? Do you even have any control over that here?

What kind of works currently (although a bit fragile) is that citations are in general are rendered, but revert to the unrendered form as soon as the cursor moves over them.

**Comment by bdarcus** [comment]
> What kind of works currently (although a bit fragile) is that citations are in general rendered, but revert to the unrendered form as soon as the cursor moves over them.

Main thing is it's easy to add or edit locators and such after the fact.

On the linked issue, BTW, we're thinking through some at-point "follow" functionality.

**Comment by bdarcus** [comment]
PR related to the follow issue. I can't really test it ATM either, but FYI:

https://github.com/bdarcus/bibtex-actions/pull/143

**Comment by bdarcus** [comment]
What's the status of possibly including this in oc-csl?

I'm putting together a PR for the Doom biblio module, which currently includes this, but a) I'd prefer some stability longer term, and b) ideally this would be in the core csl processor.

https://github.com/hlissner/doom-emacs/pull/5212

WDYT?

**Comment by andras-simonyi** [comment]
> What's the status of possibly including this in oc-csl?
> 
> I'm putting together a PR for the Doom biblio module, which currently includes this, but a) I'd prefer some stability longer term, and b) ideally this would be in the core csl processor.
> 
I have a relatively small todo list for this:
- implement Nicolas's improvement suggestions,
- ad support for subtitles,
- improve caching,
- add some tests.
I think this will take only a few days. Afterwards in theory it can be added to Org, although I'm a bit worried about how long that will take (paperwork etc.).

> [hlissner/doom-emacs#5212](https://github.com/hlissner/doom-emacs/pull/5212)
> 
> WDYT?

**Comment by bdarcus** [comment]
> * I'm a bit worried about how long that will take (paperwork etc.).

I've seen some developers who recently went through this process, and were surprised how easy it was. I believe it can happen over email IIRC.

**Comment by bdarcus** [comment]
> I've seen some developers who recently went through this process, and were surprised how easy it was. I believe it can happen over email IIRC.

This is an example, with instructions:

https://github.com/oantolin/embark/issues/233#issuecomment-850857660

**Comment by bdarcus** [comment]
Just FYi, I'm working in PR to include org-cite in doom Emacs.

Do you think this is something I should consider adding now, or wait, pending issues discussed above, including adding to oc-csl?

**Comment by bdarcus** [comment]
> I have a relatively small todo list for this:

So what's the status of this todo list at this point?

**Comment by andras-simonyi** [comment]
Well, I've just sent a patch to the Org mailing list which adds support for nocite citations, I guess this package has to handle this somehow because otherwise nocite citation will be totally hidden. Otherwise, I have some ideas for improvements but none of the seem to be critical.

**Comment by andras-simonyi** [comment]
> So what's the status of this todo list at this point?

For what it's worth, I've implemented most of the things I planned and what proved to be manageable, so I consider the package "ready for consumption" at least for now.
