### ISSUE TITLE
render without parens?

### ISSUE THREAD

**Issue by notuntoward** [andras-simonyi/org-cite-csl-activate#4]
This is great!  Is there an option to make it render without the enclosing parens, the way some websites display URL links?

**Comment by andras-simonyi** [comment]
First of all, apologies for reacting only now. As the updated README says, the CSL style used for rendering can be changed by setting the variable `org-cite-csl-activate-use-document-style`, so in theory you could set this to a style without enclosing brackets.

**Comment by andras-simonyi** [comment]
In absence of objections I'll close this issue shortly.
